[tool.pylint."MESSAGES CONTROL"]
disable = [
    "fixme",
    "invalid-name",
    "import-error",
    "line-too-long",
    "duplicate-code",
    "missing-timeout",
    "ungrouped-imports",
    "wrong-import-order",
    "superfluous-parens",
    "missing-class-docstring",
    "missing-module-docstring",
    "missing-function-docstring"
]
ignore = ["dhscanner"]

[tool.mypy]
exclude = "^dhscanner/"
ignore_missing_imports = true