services:

  parsers:
    image: orenishdocker/dhscanner-parsers:1.0.56-x64
    networks:
      - dhscanner
  
  codegen:
    image: orenishdocker/dhscanner-codegen:1.0.15-x64
    networks:
      - dhscanner
  
  kbgen:
    image: orenishdocker/dhscanner-kbgen:1.0.18-x64
    networks:
      - dhscanner
  
  queryengine:
    image: orenishdocker/dhscanner-pyswipl:1.0.6-x64
    networks:
      - dhscanner
