x-shared-transient-storage-path-anchor: &shared-transient-storage-path
  SHARED_STORAGE: /app/transient_storage

x-shared-transient-storage-anchor: &shared-transient-storage
  - transient_storage:/app/transient_storage

services:
  native_parser:
    build:
      context: ../
      dockerfile: workers/Dockerfile
      args:
        WORKER: native_parser
    volumes:
      *shared-transient-storage
    environment:
      <<: *shared-transient-storage-path
    networks:
      - dhscanner

  dhscanner_parser:
    build:
      context: ../
      dockerfile: workers/Dockerfile
      args:
        WORKER: dhscanner_parser
    volumes:
      *shared-transient-storage
    environment:
      <<: *shared-transient-storage-path
    networks:
      - dhscanner

  codegen_worker:
    build:
      context: ../
      dockerfile: workers/Dockerfile
      args:
        WORKER: codegen
    volumes:
      *shared-transient-storage
    environment:
      <<: *shared-transient-storage-path
    networks:
      - dhscanner

  kbgen_worker:
    build:
      context: ../
      dockerfile: workers/Dockerfile
      args:
        WORKER: kbgen
    volumes:
      *shared-transient-storage
    environment:
      <<: *shared-transient-storage-path
    networks:
      - dhscanner

  queryengine_worker:
    build:
      context: ../
      dockerfile: workers/Dockerfile
      args:
        WORKER: queryengine
    volumes:
      *shared-transient-storage
    environment:
      <<: *shared-transient-storage-path
    networks:
      - dhscanner

  results_worker:
    build:
      context: ../
      dockerfile: workers/Dockerfile
      args:
        WORKER: results
    volumes:
      *shared-transient-storage
    environment:
      <<: *shared-transient-storage-path
    networks:
      - dhscanner

volumes:
  transient_storage:

networks:
  dhscanner: