services:

  frontjs:
    build:
      context: ../dhscanner.core/dhscanner.service.fronts/js
      dockerfile: Dockerfile
    networks:
      - dhscanner

  frontts:
    build:
      context: ../dhscanner.core/dhscanner.service.fronts/ts
      dockerfile: Dockerfile
    networks:
      - dhscanner

  frontgo:
    build:
      context: ../dhscanner.core/dhscanner.service.fronts/go
      dockerfile: Dockerfile
    networks:
      - dhscanner

  frontphp:
    build:
      context: ../dhscanner.core/dhscanner.service.fronts/php
      dockerfile: Dockerfile
    networks:
      - dhscanner

  frontpy:
    build:
      context: ../dhscanner.core/dhscanner.service.fronts/py
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-Asia/Jerusalem}
    networks:
      - dhscanner

  frontcs:
    build:
      context: ../dhscanner.core/dhscanner.service.fronts/cs
      dockerfile: Dockerfile
    networks:
      - dhscanner

  frontrb:
    build:
      context: ../dhscanner.core/dhscanner.service.fronts/rb
      dockerfile: Dockerfile
    networks:
      - dhscanner
